name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint code 🧹
        run: |
          uv run ruff check tests/ pivotal/

      # - name: Type check 🏷
      #   run: |
      #     uv run ty check pivotal/ tests/

      - name: Run tests 🧪
        run: |
          uv run pytest --no-cov --doctest-modules
